export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/sbs3zlh.css" />
      </head>
      <body
        className={`antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
