import Banner from "@/components/banner";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/sbs3zlh.css" />
      </head>
      <body
        className={`antialiased bg-white`}
      >
        <Header/>
        <div className="bg-neutral-pearl text-neutral-charcoal min-h-1/2">
          {children}
        </div>
        <Banner/>
        <Footer/>
      </body>
    </html>
  );
}
