import Banner from "@/components/banner";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/sbs3zlh.css" />
      </head>
      <body
        className={`antialiased bg-background text-foreground`}
      >
        <Header/>
        {children}
        {/* <Banner/> */}
        <Footer/>
      </body>
    </html>
  );
}
